language: ruby
cache: bundler
bundler_args: --without development
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq wbritish
script:
 - RAILS_ENV=test GOVUK_APP_DOMAIN=test.example.com bundle exec rake spec
rvm:
  - 2.1.2
notifications:
  email:  false
