development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  host: localhost
  username: root
  password:
  database: tariffs_development

test:
  adapter: mysql2
  pool: 5
  encoding: utf8
  database: tariff_test
  username: tariff
  password: tariff
  host: localhost

production:
  adapter: mysql2
  pool: 5
  encoding: utf8
  database: tariffs_production
  username:
  password:
  host: localhost
